      queryParameters:
        orderBy:
          description: |
            Order by field: <<fieldsList>>
          type: string
          required: false
          default: <<dafault>>
        order:
          description: Order
          enum: [desc, asc]
          default: desc
          required: false
